#! /bin/sh

NAME="tgbot"
DESC="Telegram bot service"
PIDFILE="/var/run/${NAME}.pid"
LOGFILE="/var/log/${NAME}.log"

DAEMON="/usr/local/bin/python3"

# Path of your php script
DAEMON_OPTS="/home/danno/tgbot/tgbot.py"


#START_OPTS="--start --background --make-pidfile --pidfile ${PIDFILE} --exec ${DAEMON} ${DAEMON_OPTS}"
#START_OPTS="--start --background --make-pidfile --pidfile ${PIDFILE} --startas \"${DAEMON} ${DAEMON_OPTS}\""
STOP_OPTS="--stop --pidfile ${PIDFILE}"

set -e

case "$1" in
start)
echo -n "Starting ${DESC}: "
#start-stop-daemon $START_OPTS >> $LOGFILE
start-stop-daemon --start --quiet  \
 --make-pidfile --pidfile $PIDFILE --background       \
 --startas /bin/bash -- -c "exec $DAEMON $DAEMON_OPTS > /var/log/some.log"
echo "$NAME."
;;
stop)
echo -n "Stopping $DESC: "
start-stop-daemon $STOP_OPTS
echo "$NAME."
rm -f $PIDFILE
;;
restart|force-reload)
echo -n "Restarting $DESC: "
start-stop-daemon $STOP_OPTS
sleep 1
start-stop-daemon $START_OPTS >> $LOGFILE
echo "$NAME."
;;
*)
N=/etc/init.d/$NAME
echo "Usage: $N {start|stop|restart|force-reload}" >&2
exit 1
;;
esac

exit 0
